# Site settings
title: SenSyt
email: contact@sensyt.io
description: > Security data analytics consulting. Infrastructure and
  data science services focusing on security applications. We also provide
  training in several areas including malware analysis, security fundmentals,
  data science, and more.
baseurl: "/"
url: "http://sensyt.io # 
#twitter_username: jekyllrb
github_username: sensyt 
# Build settings
markdown: kramdown
